// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DCheckbox: typeof import('./src/components/design/DCheckbox.vue')['default']
    DDialog: typeof import('./src/components/design/DDialog.vue')['default']
    DFilledButton: typeof import('./src/components/design/DFilledButton.vue')['default']
    DIconButton: typeof import('./src/components/design/DIconButton.vue')['default']
    DModelDialog: typeof import('./src/components/design/DModelDialog.vue')['default']
    DSelect: typeof import('./src/components/design/DSelect.vue')['default']
    DTextInput: typeof import('./src/components/design/DTextInput.vue')['default']
    ModalDialog: typeof import('./src/components/controls/ModalDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
