// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamsNPlayers.Infrastructure.EFCore;

#nullable disable

namespace TeamsNPlayers.Infrastructure.EFCore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221023155231_CreateIndividuals")]
    partial class CreateIndividuals
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("TeamsNPlayers.Application.Individuals.Individual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.HasKey("Id");

                    b.ToTable("individuals", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ed774e4c-5fb6-48b1-b8fa-61793cbbdc50"),
                            FirstName = "John",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = new Guid("899340ea-841c-473f-a0d6-093d2bbe1474"),
                            FirstName = "Jane",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = new Guid("4e0fc4d0-7cfb-4fc9-b5b5-51789e9787cb"),
                            FirstName = "Edgar",
                            LastName = "Allan Poe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
